### ISSUE TITLE
The redirect doesn't happen when requesting oauth token

### ISSUE THREAD

**Issue by heaven** [upwork/ruby-upwork#10]
I do use `Upwork::Api::Client` to get an auth token, first I get the auth URL:
```ruby
%a{ :href => upwork_client.get_authorization_url } add one now
```
User clicks it and instead of being redirected back to my app I see this screen:
<img width="1551" alt="screen shot 2017-09-29 at 23 35 39" src="https://user-images.githubusercontent.com/126732/31035042-2f14b8ce-a56f-11e7-9fe9-1a619c68da2c.png">

**Comment by heaven** [comment]
It behaves like if it was a desktop application but I selected `Web project` and specified a callback URL when applying for a key.

**Comment by upwyy** [comment]
Thanks for the report, looking into it.

**Comment by mnovozhylov** [comment]
@heaven , thanks for your report!
Please, contact apisupport@ and provide the full details, i.e. your API Key and other data you have. It will help us investigate the possible issue quicker.

**Comment by mnovozhylov** [comment]
@heaven 
thank you for contacting us and paying our attention to this behavior!
Actually, that's not a bug on the backend side. Historically, the library was created without the support to bypass oauth_callback parameter explicitly. And by default, the native oauth1 library sets the parameter to 'oob' when it executes get_request_token. As a result, authorization screen sees that oauth_callback was set to 'oob' and ignores callback parameter.

We update ruby-upwork library (v1.2.2) and extend it with the possibility of setting up oauth_callback parameter on the authorization step.

**Comment by mnovozhylov** [comment]
@heaven v1.2.2 has been released. Please, pay attention that additionally, you need to specify the callback URL explicitly in your application, like:
`client.get_authorization_url "https://www.upwork.com"`.

Have fun!
