### ISSUE TITLE
Work Diary endpoint

### ISSUE THREAD

**Issue by trueinviso** [upwork/ruby-upwork#13]
It would be awesome if you guys added endpoints to the API for creating time in the work diary.

It would be nice to be able to integrate other third party time tracking apps with Upwork (i.e. Harvest), so that you could export time from Harvest to the proper Upwork work diary.

**Comment by mnovozhylov** [comment]
hi @trueinviso ,

regarding new APIs, please, contact our [Support Team](https://support.upwork.com/hc/en-us).
