### ISSUE TITLE
NameError: uninitialized constant Upwork::Api::Routers::Jobs

### ISSUE THREAD

**Issue by alexbezhan** [upwork/ruby-upwork#3]
I'm new to ruby, but I'm getting error when trying to search for jobs
`NameError: uninitialized constant Upwork::Api::Routers::Jobs`

I've added `gem 'upwork-api'` to Gemfile and runned `bundle install`.

**Comment by mnovozhylov** [comment]
@OleksandrBezhan , see the example and require proper class in your application.
