### ISSUE TITLE
503 "Service Unavailable" (Net::HTTPFatalError)

### ISSUE THREAD

**Issue by hassanakram** [upwork/ruby-upwork#8]
I have only `consumer_key` and `consumer_secret` so commented these lines provided in example:  

```
'access_token'    => 'xxxxxxxx',# assign if known
'access_secret'   => 'xxxxxxxx',# assign if known
```

When I try to run the example, **503 "Service Unavailable" (Net::HTTPFatalError)** exception is thrown.

The trace of stack is as following:

```
/Users/HASSAN/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/http/response.rb:119:in `error!': 503 "Service Unavailable" (Net::HTTPFatalError)
	from /Users/HASSAN/.rvm/gems/ruby-2.1.2/gems/oauth-0.5.1/lib/oauth/consumer.rb:218:in `token_request'
	from /Users/HASSAN/.rvm/gems/ruby-2.1.2/gems/oauth-0.5.1/lib/oauth/consumer.rb:136:in `get_request_token'
	from /Users/HASSAN/.rvm/gems/ruby-2.1.2/gems/upwork-api-1.2.0/lib/upwork/api/client.rb:54:in `get_authorization_url'
	from upwork.rb:34:in `<main>'
```

**Comment by mnovozhylov** [comment]
@hassanakram , unfortunately, you message has incomplete description and it has nothing to do with library itself, i.e. response is returned by the server, not by the library. Please, contact apisupport@ in case you have any questions regarding usage of your API Key.
